### ISSUE TITLE
encode or protect?

### ISSUE THREAD

**Issue by arademaker** [vwochnik/jekyll-email-protect#1]
please consider rewrite the example to make it clear if the filter is `protect_email` or `encode_email`?

BTW, any idea about how we could implement a client-side solution like:

http://www.projecthoneypot.org/how_to_avoid_spambots_3.php
http://stackoverflow.com/questions/483212/effective-method-to-hide-email-from-spam-bots

?

**Comment by vwochnik** [comment]
> please consider rewrite the example to make it clear if the filter is protect_email or encode_email?

Well, the repository is now named differently then the Liquid filter but I won't change that.

Now, for the client-side encoding: This plugin is specifically made for server-side encoding of e-mail addresses which GitHub uses in a similar fashion. Just look at the e-mail address on your profile page.

**Comment by arademaker** [comment]
Sorry, I was not talking about the name of the repo, I was just mentioning that in the README file you are using two different 'filters': encode_email and protect_email!

https://github.com/vwochnik/jekyll-email-protect#getting-started

```
 {{ 'example@example.com' | encode_email }}
```

https://github.com/vwochnik/jekyll-email-protect#example

```
 <a href="mailto:{{ site.email | protect_email }}" title="Contact me">Contact me</a>
```

**Comment by vwochnik** [comment]
The filter is called `encode_email`.
