### ISSUE TITLE
Does not seem to work with Jekyll 3.7.0?

### ISSUE THREAD

**Issue by tjkohli** [vwochnik/jekyll-email-protect#5]
Hi! This tag doesn't seem to encode the email anymore. I installed using the: `gem install jekyll-email-protect` command and use it like this: `{{ site.email | encode_email }}`

Please advise!

**Comment by andreySadomovskiy** [comment]
Have the same issue.

**Comment by vwochnik** [comment]
You have to add it to your `_config.yml` with:

```
plugins:
- jekyll-email-protect
```

**Comment by andreySadomovskiy** [comment]
Thank you!
