### ISSUE TITLE
 Another encode format for emails. 

### ISSUE THREAD

**Issue by andreySadomovskiy** [vwochnik/jekyll-email-protect#6]
Is it possible to add one more encode format  for emails to have possibility to show email link name on HTML page?  To encode not only `href`, but link name also.

For example:  [&#121;&#111;&#117;&#114;&#110;&#097;&#109;&#101;&#064;&#100;&#111;&#109;&#097;&#105;&#110;&#046;&#099;&#111;&#109;](&#121;&#111;&#117;&#114;&#110;&#097;&#109;&#101;&#064;&#100;&#111;&#109;&#097;&#105;&#110;&#046;&#099;&#111;&#109;)
```
<a href="mailto:
&#121;&#111;&#117;&#114;&#110;&#097;&#109;&#101;&#064;&#100;&#111;&#109;&#097;&#105;&#110;&#046;&#099;&#111;&#109;">
&#121;&#111;&#117;&#114;&#110;&#097;&#109;&#101;&#064;&#100;&#111;&#109;&#097;&#105;&#110;&#046;&#099;&#111;&#109;
</a>
```

**Comment by vwochnik** [comment]
Added and published. You can now do this:

```
<a href="mailto:{{ site.email | encode_email }}">{{ site.email | html_encode_email }}</a>
```

**Comment by andreySadomovskiy** [comment]
What I am doing wrong? 

I have updated plugin:   `gem update jekyll-email-protect`
Updated code as in example  `<a href="mailto:{{ site.email.sales | encode_email }}">{{ site.email.sales | html_encode_email }}</a>`  but `href ` is encoded and link name not.

**Comment by andreySadomovskiy** [comment]
I found the reason —  `Gemfile.lock` 

Many thanks!
